# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' POS tagging in C++
#'
#' @keywords internal
pos_cpp_vec <- function(inputs, model_path) {
    .Call('_RcppJagger_pos_cpp_vec', PACKAGE = 'RcppJagger', inputs, model_path)
}

#' POS tagging in C++ (only token and pos)
#'
#' @keywords internal
pos_simple_cpp_vec <- function(inputs, model_path) {
    .Call('_RcppJagger_pos_simple_cpp_vec', PACKAGE = 'RcppJagger', inputs, model_path)
}

#' Tokenizer (a vector input)
#'
#' @keywords internal
tokenize_cpp_vec <- function(inputs, model_path, keep_vec, keep_all) {
    .Call('_RcppJagger_tokenize_cpp_vec', PACKAGE = 'RcppJagger', inputs, model_path, keep_vec, keep_all)
}

#' Lemmatize (a vector input)
#'
#' @keywords internal
lemmatize_cpp_vec <- function(inputs, model_path, keep_vec, keep_all) {
    .Call('_RcppJagger_lemmatize_cpp_vec', PACKAGE = 'RcppJagger', inputs, model_path, keep_vec, keep_all)
}

